version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: airflow-postgres
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - airflow_network
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-standalone
    depends_on:
      - postgres
    environment:
      - LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Standalone 모드
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./airflow/dags:/opt/airflow/dags
#      - ./airflow/udfs:/opt/airflow/udfs
      - ./airflow/udfs/utils:/opt/airflow/udfs/utils
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ./fwani_airflow_plugin:/opt/airflow/plugins/fwani_airflow_plugin
    ports:
      - "8082:8080"  # Airflow 웹 UI 포트
      - "5678:5678"  # PyCharm Debug 포트 추가
    entrypoint: ["/entrypoint.sh"]
    networks:
      - airflow_network
networks:
  airflow_network:
    driver: bridge
