version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: airflow-postgres
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - workflow_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow", "-d", "airflow" ]
      interval: 5s
      retries: 5
      timeout: 3s
  airflow:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    container_name: airflow-standalone
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - PYCHARM_DEBUG_ENABLED=True
      - LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Standalone 모드
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - PYTHONPATH=/opt/airflow/udfs:/opt/airflow/plugins:$PYTHONPATH
    volumes:
      - ./docker/airflow.entrypoint.sh:/entrypoint.sh
      - ./server/data/dags:/opt/airflow/dags
      - ./server/data/udfs:/opt/airflow/udfs
      - ./server/data/shared:/app/shared
      - ./server/data/logs:/opt/airflow/logs
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - /var/run/docker.sock:/run/docker.sock  # ✅ M2 Mac 환경 적용
    ports:
      - "8082:8080"  # Airflow 웹 UI 포트
    entrypoint: [ "/entrypoint.sh" ]
    networks:
      - workflow_network
  workflow:
    build:
      context: .
      dockerfile: docker/fwani-flow.Dockerfile
    container_name: workflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_URI=postgresql://airflow:airflow@postgres:5432/workflow
      - LOG_DIR=/app/logs
      - DAG_DIR=/app/dags
      - UDF_DIR=/app/udfs
      - SHARED_DIR=/app/shared
    volumes:
      - ./docker/workflow.entrypoint.sh:/entrypoint.sh
      - ./server/data/dags:/app/dags
      - ./server/data/udfs:/app/udfs
      - ./server/data/shared:/app/shared
      - ./server/data/logs:/app/logs
    ports:
      - "5052:5050"  # FastAPI port
    entrypoint: [ "/entrypoint.sh" ]
    networks:
      - workflow_network
networks:
  workflow_network:
    driver: bridge
